version: '3'
services:
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./nodejs/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./nodejs/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to create tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  backend:
    container_name: back
    build: ./nodejs
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    container_name: front
    build: ./react
    ports:
      - "3000:3000"
    depends_on:
      - backend